name: CastleWars
description: This is minigame created by EMU mapmaking as a passion project.
version: '${version}'
authors: [CookieBeans902]
softdepend: [LuckPerms]
website: https://emumaps.me
main: me.emumaps.castlewars.CastleWars
paperPluginLoader: me.emumaps.castlewars.CastleWarsLoader
api-version: '1.21.11'
load: POSTWORLD
